name: chumaki
description: A trade game based in Ukraine of XVIII century.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tuple: ^2.0.0
  rxdart: ^0.26.0
  clock: ^1.0.1
  intl: ^0.17.0
  uuid: ^3.0.4
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.5
  google_fonts: ^2.1.0
  fake_async: ^1.2.0
  just_audio: ^0.8.0
  page_flip_builder: ^0.1.3
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - images/
    - images/ui/
    - images/wagon/
    - images/events/
    - images/resources/cannon/
    - images/resources/charcoal/
    - images/resources/firearm/
    - images/resources/fish/
    - images/resources/bread/
    - images/resources/fur/
    - images/resources/grains/
    - images/resources/horse/
    - images/resources/ironore/
    - images/resources/metalparts/
    - images/resources/money/
    - images/resources/planks/
    - images/resources/powder/
    - images/resources/stone/
    - images/resources/wood/
    - images/resources/silk/
    - images/resources/salt/
    - images/resources/wool/
    - images/resources/gorilka/
    - images/resources/honey/
    - images/resources/wax/
    - images/resources/tobacco/
    - images/resources/amber/
    - images/resources/cloth/
    - images/cities/
    - images/cities/avatars/
    - images/icons/market/
    - images/icons/military/
    - images/icons/cloths/
    - images/icons/food/
    - images/icons/lock/
    - images/icons/resources/
    - images/icons/luxury/
    - images/icons/paths/
    - images/icons/money/
    - images/icons/unknown/
    - images/icons/flags/
    - images/icons/wagon/
    - images/events/vesterfeld/
    - images/leaders/
    - images/manufacturings/
    - images/manufacturings/cannon_foundry/
    - images/manufacturings/forest/
    - images/manufacturings/field/
    - images/manufacturings/river/
    - images/manufacturings/iron_mine/
    - images/manufacturings/marketplace/
    - images/manufacturings/trappers_house/
    - images/manufacturings/mill/
    - images/manufacturings/quarry/
    - images/manufacturings/powder_cellar/
    - images/manufacturings/shooting_range/
    - images/manufacturings/smith/
    - images/manufacturings/stables/
    - images/manufacturings/sawmill/
    - images/manufacturings/charcoal_maker/
    - images/manufacturings/smeltery/
    - images/manufacturings/cart_maker/
    - images/manufacturings/boat_maker/
    - images/manufacturings/pasture/
    - images/manufacturings/weavery/
    - images/manufacturings/liman/
    # SOUNDS
    - assets/sounds/
    # OTHER
    - images/other/