name: chumaki
description: A trade game based in Ukraine of XVIII century.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tuple: ^2.0.0
  rxdart: ^0.26.0
  clock: ^1.0.1
  intl: ^0.17.0
  uuid: ^3.0.4
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/wagon/
    - images/resources/cannon/
    - images/resources/charcoal/
    - images/resources/firearm/
    - images/resources/fish/
    - images/resources/bread/
    - images/resources/fur/
    - images/resources/grains/
    - images/resources/horse/
    - images/resources/ironore/
    - images/resources/metalparts/
    - images/resources/money/
    - images/resources/planks/
    - images/resources/powder/
    - images/resources/stone/
    - images/resources/wood/
    - images/resources/silk/
    - images/resources/salt/
    - images/resources/wool/
    - images/resources/gorilka/
    - images/cities/
    - images/cities/avatars/